---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ct-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ct-backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: ct-backend
    spec:
      containers:
      - name: ct-backend
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
            memory: 512M
          limits:
            cpu: 500m
            memory: 512M
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              key: DB_HOST
              name: clevertech-vars
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              key: DB_USERNAME
              name: clevertech-vars
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: DB_PASSWORD
              name: clevertech-vars
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              key: DB_DATABASE
              name: clevertech-vars
        - name: PORT
          valueFrom:
            configMapKeyRef:
              key: BE_PORT
              name: clevertech-vars
