---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: 200m
            memory: 512M
          limits:
            cpu: 1000m
            memory: 1G
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_USER
              name: clevertech-vars
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PASSWORD
              name: clevertech-vars
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: clevertech-vars
        volumeMounts:
        - name: "files"
          mountPath: "/tmp/courses.csv"
          subPath: "courses.csv"
        - name: "files"
          mountPath: "/docker-entrypoint-initdb.d/initdb.sql"
          subPath: "initdb.sql"
      restartPolicy: Always
      volumes:
        - name: "files"
          configMap:
            name: "files"
